name: Deploy Workflow
on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: deploy container
              run: docker run --name dvna -p 9090:9090 -d appsecco/dvna:sqlite