name: Deploy Workflow
on: push

jobs:
    deploy_and_scan:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Deploy Container
              run: docker run --name dvna -p 9090:9090 -d appsecco/dvna:sqlite
            - name: ZAP Scan
              uses: zaproxy/action-baseline@v0.6.1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
                target: 'http://127.0.0.1:9090/login'
                rules_file_name: '.zap/rules.tsv'
                cmd_options: '-a'